name: Build __TAG__ image

on:
  push:
    branches:
      - main
    tags:
      - "__PERL_VERSION__-__VARIANT__/*"
  pull_request:
    paths:
      - ".github/workflows/__PERL_VERSION__-__VARIANT__.yml"
      - "dockerfiles/__PERL_VERSION__/__VARIANT__/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.42"
      - name: build
        run: ./scripts/build.pl __PERL_VERSION__ __VARIANT__

      - name: Publish to DockerHub
        env:
          USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          printenv PASSWORD | docker login --username "$USERNAME" --password-stdin
          ./scripts/publish.pl "$USERNAME/p5-aws-lambda" __PERL_VERSION__ __VARIANT__ __TAG__
          docker logout

      - name: Publish to GitHub Packages Container registry
        env:
          USERNAME: ${{ github.repository_owner }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printenv PASSWORD | docker login --username "$USERNAME" --password-stdin ghcr.io
          ./scripts/publish.pl "ghcr.io/$USERNAME/p5-aws-lambda" __PERL_VERSION__ __VARIANT__ __TAG__
          docker logout ghcr.io

      - name: Configure AWS Credentials
        uses: fuller-inc/actions-aws-assume-role@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::445285296882:role/lambda-perl5-runtime-ecr-DeploymentRole-199JZ5SP862Q0
          role-session-tagging: true
      - name: Publish to ECR Public Registry
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/shogo82148
          ./scripts/publish.pl "public.ecr.aws/shogo82148/p5-aws-lambda" __PERL_VERSION__ __VARIANT__ __TAG__
          docker logout public.ecr.aws/shogo82148
