name: Build build-5.40.al2 image

on:
  push:
    branches:
      - main
    tags:
      - "5.40-build.al2/*"
  pull_request:
    paths:
      - ".github/workflows/5.40-build.al2.yml"
      - "dockerfiles/5.40/build.al2/**"
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: shogo82148/actions-setup-perl@a198315ec4e9244f206879ea7b63078003aec8a6 # v1.41.1
        with:
          perl-version: "5.42"
      - name: build
        run: ./scripts/build.pl 5.40 build.al2

      - name: Publish to DockerHub
        env:
          USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          printenv PASSWORD | docker login --username "$USERNAME" --password-stdin
          ./scripts/publish.pl "$USERNAME/p5-aws-lambda" 5.40 build.al2 build-5.40.al2
          docker logout

      - name: Publish to GitHub Packages Container registry
        env:
          USERNAME: ${{ github.repository_owner }}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          printenv PASSWORD | docker login --username "$USERNAME" --password-stdin ghcr.io
          ./scripts/publish.pl "ghcr.io/$USERNAME/p5-aws-lambda" 5.40 build.al2 build-5.40.al2
          docker logout ghcr.io

      - name: Configure AWS Credentials
        uses: fuller-inc/actions-aws-assume-role@c6cc1f39a57c0228a4b542ae2b3d49d3e56ce85a # v1.9.1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::445285296882:role/lambda-perl5-runtime-ecr-DeploymentRole-199JZ5SP862Q0
          role-session-tagging: true
      - name: Publish to ECR Public Registry
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/shogo82148
          ./scripts/publish.pl "public.ecr.aws/shogo82148/p5-aws-lambda" 5.40 build.al2 build-5.40.al2
          docker logout public.ecr.aws/shogo82148
