name: create new release

on:
  workflow_dispatch:
  schedule:
    - cron: "4 7 * * *"

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # secrets.GITHUB_TOKEN doesn't start a new workflow run, but we want.
      - id: generate
        uses: shogo82148/actions-github-app-token@84232dc4d9bd875d4dd83e3e5c4705db1c98a997 # v1.3.1

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ steps.generate.outputs.token }}
          fetch-depth: 0 # we need all tags

      - uses: shogo82148/actions-setup-perl@3d3cb73ca65d657a809d97eab324d4e4f140bf5e # v1.42.0
        with:
          perl-version: "5.40"

      - run: ./scripts/release.pl --force
