name: create new release

on:
  workflow_dispatch:
  schedule:
    - cron: "4 7 * * *"

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # secrets.GITHUB_TOKEN doesn't start a new workflow run, but we want.
      - id: generate
        uses: shogo82148/actions-github-app-token@d75b03a80d0450d087a12b72dff2d987a4ced993 # v1.3.0

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.generate.outputs.token }}
          fetch-depth: 0 # we need all tags

      - uses: shogo82148/actions-setup-perl@922d4ec780f14b8ff6d6e09c15d5eaee240b23a0 # v1.40.1
        with:
          perl-version: "5.40"

      - run: ./scripts/release.pl --force
