name: update

on:
  schedule:
    - cron: "4 7 * * *"
  workflow_dispatch:

concurrency:
  group: update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    # ref. https://github.com/fuller-inc/actions-aws-assume-role#about-security-hardening-with-openid-connect
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: install docker-tags
        run: |
          cd /tmp
          curl -sSL https://github.com/koki-develop/docker-tags/releases/download/v0.9.0/docker-tags_Linux_x86_64.tar.gz | tar xz
          sudo mv docker-tags /usr/local/bin/

      - uses: shogo82148/actions-setup-perl@3d3cb73ca65d657a809d97eab324d4e4f140bf5e # v1.42.0
        with:
          perl-version: "5.44"
      - name: Configure AWS Credentials
        uses: fuller-inc/actions-aws-assume-role@c6cc1f39a57c0228a4b542ae2b3d49d3e56ce85a # v1.9.1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::445285296882:role/lambda-perl5-runtime-ecr-DeploymentRole-199JZ5SP862Q0
          role-session-tagging: true

      - name: Update Dockerfile
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./scripts/update.sh

      # commit and push
      - id: generate
        uses: shogo82148/actions-github-app-token@84232dc4d9bd875d4dd83e3e5c4705db1c98a997 # v1.3.1
      - name: Commit and push
        uses: shogo82148/actions-commit-and-create-pr@b1322fe9da4037e9720e34ea221997cffcd3498d # v1.1.4
        with:
          github-token: ${{ steps.generate.outputs.token }}
