name: update

on:
  schedule:
    - cron: "4 7 * * *"
  workflow_dispatch:

concurrency:
  group: update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest

    # ref. https://github.com/fuller-inc/actions-aws-assume-role#about-security-hardening-with-openid-connect
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.38"
      - name: Configure AWS Credentials
        uses: fuller-inc/actions-aws-assume-role@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::445285296882:role/lambda-perl5-runtime-ecr-DeploymentRole-199JZ5SP862Q0
          role-session-tagging: true

      - name: Update Dockerfile
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./scripts/update.sh

      # commit and push
      - id: generate
        uses: shogo82148/actions-github-app-token@v1
      - name: Commit and push
        uses: shogo82148/actions-commit-and-create-pr@v1
        with:
          github-token: ${{ steps.generate.outputs.token }}
